// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_MkLHmSTFmeyj6Eg9AfhDQfnc7Uz_v8Q',
    appId: '1:191902719239:web:6fdefaaebf4a3bc802f9a2',
    messagingSenderId: '191902719239',
    projectId: 'plantas-caa2e',
    authDomain: 'plantas-caa2e.firebaseapp.com',
    storageBucket: 'plantas-caa2e.appspot.com',
    measurementId: 'G-1SB26X6H9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDodzmgLcp5Iudr3YwGCYH8s7cQQUpmGPA',
    appId: '1:191902719239:android:2c9aad069ce3aab802f9a2',
    messagingSenderId: '191902719239',
    projectId: 'plantas-caa2e',
    storageBucket: 'plantas-caa2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkKBEYM_ina8umSOK9Y9RLZgsZHqn_L5E',
    appId: '1:191902719239:ios:dd733e2cde42cd9202f9a2',
    messagingSenderId: '191902719239',
    projectId: 'plantas-caa2e',
    storageBucket: 'plantas-caa2e.appspot.com',
    iosClientId: '191902719239-h73b6hjakio6oef5qknhhr4p7no3dg0b.apps.googleusercontent.com',
    iosBundleId: 'com.nabenik.plantas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkKBEYM_ina8umSOK9Y9RLZgsZHqn_L5E',
    appId: '1:191902719239:ios:dd733e2cde42cd9202f9a2',
    messagingSenderId: '191902719239',
    projectId: 'plantas-caa2e',
    storageBucket: 'plantas-caa2e.appspot.com',
    iosClientId: '191902719239-h73b6hjakio6oef5qknhhr4p7no3dg0b.apps.googleusercontent.com',
    iosBundleId: 'com.nabenik.plantas',
  );
}
